name = "LegendJuliaRegistry"
uuid = "b7237ffd-a9c3-49b0-83fb-09b4b744a062"
repo = "https://github.com/legend-exp/LegendJuliaRegistry.git"
description = "Julia packages specific to the LEGEND experiment"

[packages]
0b925020-e659-485c-98dd-189633cb4be4 = { name = "MJDSigGen", path = "M/MJDSigGen" }
18221496-77af-46cf-bab8-820da09f7f97 = { name = "LegendSpecFits", path = "L/LegendSpecFits" }
33d6da08-6349-5f7c-b5a4-6ff4d8795aaf = { name = "LegendTestData", path = "L/LegendTestData" }
59dd4b32-a3c2-596d-b22d-5bb8b5f60033 = { name = "LegendUpROOTIO", path = "L/LegendUpROOTIO" }
99e09c13-5545-5ee2-bfa2-77f358fb75d8 = { name = "LegendDataTypes", path = "L/LegendDataTypes" }
9feedd95-f0e0-423f-a8dc-de0970eae6b3 = { name = "LegendDataManagement", path = "L/LegendDataManagement" }
a36173eb-ee8f-473c-bbea-a8a9322f1a0c = { name = "LegendDetectorDesign", path = "L/LegendDetectorDesign" }
c397c909-374d-579b-8af3-fa3aa4f02e89 = { name = "LegendTextIO", path = "L/LegendTextIO" }
c9265ca6-b027-5446-b1a4-febfa8dd10b0 = { name = "LegendHDF5IO", path = "L/LegendHDF5IO" }
ca666546-4c2a-41e4-9648-72713d810efe = { name = "LegendEventAnalysis", path = "L/LegendEventAnalysis" }
ce9a434a-d062-4f11-9371-3059ddb1c48a = { name = "LegendMakie", path = "L/LegendMakie" }
e592b54b-af3c-468f-bcc7-10a913e293a7 = { name = "LegendGeSim", path = "L/LegendGeSim" }
e6d7a502-be5c-5049-a927-8d60e566555d = { name = "LegendDSP", path = "L/LegendDSP" }
